default_user_prefs = {
    "action": 0,
    "adventure": 0,
    "arcade": 0,
    "puzzle": 0,
    "simulation": 0,
    "strategy": 0,
    "rpg": 0,
    "casual": 0,
    "virtual-version": 0,
    "idle": 0,
    "musical": 0,
    "meditation": 0,
    "sensorial": 0,
    "painting": 0,
    "co-op": 0,
    "competitive": 0,
    "narrative": 0,
    "social": 0,
    "sports": 0,
}
